services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle   # <— aggiungi questa
    environment:
      - JEKYLL_ENV=development
